# Generated by Django 5.2.1 on 2025-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Laptop', 'Laptop'), ('TV', 'TV'), ('Smart Watches', 'Smart Watches')], max_length=20, null=True),
        ),
    ]
